#Test de nuestro servidor
@url = http://127.0.0.1:5500/api/v1/

############
POST {{url}}login
content-type: application/json

{
    "username": "NombreGenericoNoDeUnBOT30",
    "email": "dev@dev.com",
    "password": "$2b$10$NNmmsxy7qMPgz1TL/KVk0ORoOtit6I.TAz.yz2m9Yao42Bs5bpoWS",
    "role": "basic"
}

############
POST {{url}}login
content-type: application/json

{
    "username": "NombreGenericoNoDeUnBOT2000",
    "email": "dev@green.com",
    "password": "$2b$10$X8Keq4CsWZVhqKlOs2taTOs3YJSd8lYRyBwG1aSFfZhz99rnJTFXO",
    "role": "admin"
}